### PR TITLE
fix(icons): update system tray icons

### PR DESCRIPTION
**Pull request by MCozhusheck**
Description
---
fixes: #299 
Update system icons according to designs.

Motivation and Context
---
Fix incorrect icons.

How Has This Been Tested?
---
Just launch app and check icons in system menu.

What process can a PR reviewer use to test or verify this change?
---
Same as above.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

**Comment by stringhandler** [comment]
I think you are changing all the icons here, when only the systray icon needs to be replaced

**Comment by MCozhusheck** [comment]
> I think you are changing all the icons here, when only the systray icon needs to be replaced

Reverted change for apply new system tray icon in all cases. Now only it's applied to system tray depending to OS of the user according to [tauri docs](https://tauri.app/v1/guides/features/icons/)

**Comment by stringhandler** [comment]
I don't think these are the correct icons.

**Comment by MCozhusheck** [comment]
> I don't think these are the correct icons.

Yep I mixed up icons from designs. Now should be correct.

**Comment by brianp** [comment]
I can not build this PR. @MCozhusheck will investigate.

image

**Pull request merged**
