### PR TITLE
chore: p2pool stats page

### PR DESCRIPTION
**Pull request by mmrrnn**
Closes: [#1162](https://github.com/tari-project/universe/issues/1162)

Description
---
* Added P2pool debugging stats inside `Pool Mining` tab.
* Display & edit P2pool stats server port

Screenshots
---
Screenshot from 2024-12-03 14-55-01
Screenshot from 2024-12-03 14-54-23
Screenshot from 2024-12-03 14-54-13
Screenshot from 2024-12-03 14-54-05
Screenshot from 2024-12-03 14-50-50

### CODE REVIEW

**Comment by stringhandler** [comment]
Amazing!

Can we convert the last ping to "3 seconds ago" or something like that, rather than the timestamp

**Comment by stringhandler** [comment]
Also can the connected peers be shown as a table instead?

**Review by brianp — APPROVED** [review]
LGTM, see change request and it looks ready to merge.

**Review by MCozhusheck — APPROVED** [review]

**Comment by MCozhusheck** [comment]
I am seeing empty values but pool mining is enabled
image
I didn't see any warnings or errors in both terminal and window console

**Comment by mmrrnn** [comment]
@MCozhusheck Did you used Nextnet?

**Comment by mmrrnn** [comment]
Screenshot from 2024-12-03 16-08-04

**Comment by MCozhusheck** [comment]
> @MCozhusheck Did you use Nextnet?

dang I was testing on the esmeralda
will check on the nextnet now

**Comment by brianp** [comment]
I too saw empty values on *esme*. I also solo mine with p2pool enabled on esme all day long. There's just not enough activity there. When I ran on nextnet it works fine.

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, app version 0.8.5. I am seeing stats displayed. There is separate ticket for cleaning up the stats:
Screenshot (437)
Screenshot (438)
Screenshot (439)

**Comment by Anziskavds** [comment]
Tested successfully on MacBook Air M1 2020 13 inch on Testnet v0.8.5

**Pull request merged**
