### PR TITLE
feat: individual gpu settings

### PR DESCRIPTION
**Pull request by Misieq01**
## **Important note**
It Requires versions 0.1.19 of gpuminer. From what i saw release for this version didn't passed so to work with this PR or test it its required to build gpuminer from main locally and replace binaries until version 0.1.19 is released

### [ Summary ]
- Expanded Custom mode modal to take into account multiple gpu devices
- Expanded and adjusted max_gpu_threads and correlated fields on frontend and backend
- Fixed parsing gpu_status.json in gpu_miner
- Changed passed value to `grid_size` to include multiple gpu devices
------------
### [ What is left to do  ]
- Test it on wider range of devices

### CODE REVIEW

**Comment by brianp** [comment]
I know it's still in draft but I was trying it out and saw something funny. Although this time it did appear that the gpuminer was running, and wasn't being restarted.
Screenshot 2024-11-19 151105

**Comment by Misieq01** [comment]
> I know it's still in draft but I was trying it out and saw something funny. Although this time it did appear that the gpuminer was running, and wasn't being restarted. Screenshot 2024-11-19 151105

Oh, good catch, I'll fix it quickly

**Comment by Misieq01** [comment]
Tested on:
 Ubuntu with rtx4080 and integrated amd gpu => **Works**
 Windows with rtx4060 and integrated intel gpu => **Works**
 Apple m1 => **Not working**

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.7.2. In Custome mode, I do see my individual GPU devices however even when adjusting them, my GPU Power still shows as null on the mining widget and I still see warnings in the logs:
Screenshot (307)
Screenshot (308)

**Pull request merged**
