### PR TITLE
feat: persist window position and size

### PR DESCRIPTION
**Pull request by mmrrnn**
Description
---
When closing the window, save the current position and size in the `app_config.json` file to ensure that the next time the Tari Universe window is launched, it opens in the same position as when it was last closed.

Closes: #987

How to test it?
---
Launch the app several times, changing the window position and size between each session. Then, verify if the window's position and size remain consistent after rerun.

[Screencast from 11-25-2024 05:46:36 PM.webm](https://github.com/user-attachments/assets/d6eb9795-402a-4991-ae31-f55ffa143eb7)

### CODE REVIEW

**Review by brianp — APPROVED** [review]
I like it.

What is the technocal limitation we can't apply the same settings to the splash screen aswell?

**Comment by mmrrnn** [comment]
[Screencast from 11-26-2024 12:11:27 PM.webm](https://github.com/user-attachments/assets/f1018220-6866-45ef-9cc3-2b1f9087cb0e)

**Comment by mmrrnn** [comment]
* Unified splashscreen and main window positions and sizes.
* Improved error handling
* Save experimental settings visibility in app_config.json`

**Review by brianp — CHANGES_REQUESTED** [review]
on Mac Sequoia 15.1 everytime I start the app it goes full screen despite whatever size or position I previously had it in.

**Comment by mmrrnn** [comment]
Should be fine now:
* Couldn't save window position and size since moving event is triggered when windows is shown(with default tauri-conf values):
```
EVENT - MOVED("splashscreen"): pos: PhysicalPosition { x: 0, y: 64 } size: PhysicalSize { width: 1380, height: 780 }
EVENT - MOVED("main"): pos: PhysicalPosition { x: 0, y: 64 } size: PhysicalSize { width: 1380, height: 780 }
```
I discovered a workaround by extracting the details from the splash screen and applying them to the main window during the transition.
* Used outer positions and PhysicalSize, PhysicalPosition

**Comment by brianp** [comment]
This is looking really good.

On first run, when no window settings have been persisted into the config (upgrades). The window is *way* too small

image

**Comment by brianp** [comment]
I almost forgot. `Visual Mode` is also supposed to be persisted along with experimental settings.

**Comment by brianp** [comment]
> Visual mode is already persisted since https://github.com/tari-project/universe/pull/1043
huh. Look at that. Thanks!

**Review by brianp — APPROVED** [review]
Tested on windows and mac with great victory.

Welcome to merge town.

**Pull request merged**
