### PR TITLE
feat: detect orphan chain

### PR DESCRIPTION
**Pull request by MCozhusheck**
Description
---
Every 30 seconds fetch block from current tip minus 1000, 2000 and 3000 from both local node and text explorer and compares these 2. If they are different for just 1 case, send event to frontend which displays warning.

Motivation and Context
---
Some miners are stuck at orphan chains. This will check if it's a case for them and display information.

How Has This Been Tested?
---
Change condition to always return true in `check_if_is_orphan_chain` in `node_manager.rs` and check if alert under mining button is displayed.

Also replicated orphan chain by changing in experimental settings to not use tor and manually ban tcp peers in `minotari node` to make sure you are that there are no connected peers.

What process can a PR reviewer use to test or verify this change?
---
Same as above.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

**Comment by stringhandler** [comment]
tested, but needs to be the other way around. It should read blocks from the explorer and see if they are in the current chain

**Comment by mmrrnn** [comment]
Resolved conflicts on separate branch due to the missing write permissions: https://github.com/tari-project/universe/pull/1018

**Review by mmrrnn — APPROVED** [review]

**Review by brianp — CHANGES_REQUESTED** [review]
Mining can't start when I'm on this branch. 

I remember now I had actually tested this Friday but didn't comment.

image

**Comment by brianp** [comment]
I was testing an outdated branch. Disregard the last message. Even the screenshot reads v0.6.6. 

Once I was on the correct branch it was notable the i18n may be missing or misconfigured:

image

**Pull request merged**
