### PR TITLE
fix(restart): optional stopping miners for restart application

### PR DESCRIPTION
**Pull request by mmrrnn**
Added a flag for terminating processes before restarting the app. We don't want to kill processes during auto-updates, but in other cases we want to kill them and prevent from hanging processes and killing them after the restart.

### CODE REVIEW

**Comment by brianp** [comment]
Why don't we want to kill processes during auto-update?

**Comment by mmrrnn** [comment]
App is stopped until user decides whether he wants to update the app or not - in that case we would freeze the app trying to kill miners that hasn't even started yet

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.15. I find that when I click on `Restart Now` nothing occurs for a few seconds and gives me the impression that the CTA is not working before the app eventually closes. As a user this experience is not ideal for me as I almost closed the app manually thinking that perhaps it may have frozen etc

**Comment by Anziskavds** [comment]
Tested on MacBook Air 13 inch M1 2020 and I also experience the delay when clicking on the ``Restart now`` button. I've experienced this on Testnet v0.6.16

**Pull request merged**
