### PR TITLE
fix(firewall): handle firewall rules on windows

### PR DESCRIPTION
**Pull request by mmrrnn**

### CODE REVIEW

**Comment by mmrrnn** [comment]
There is an issue with setup wizard. Tari Universe is not auto-running after installation

**Comment by brianp** [comment]
Holding off on this PR until next week.

**Comment by mmrrnn** [comment]
Since we have our custom installer: https://github.com/tari-project/universe/pull/897

We can handle setting windows firewalls there and fix the issue with auto-start

**Review by brianp — CHANGES_REQUESTED** [review]
Can't build on windows:

```
   Compiling tari-universe v0.6.4 (C:\Users\brian\Projects\universe\src-tauri)
error[E0432]: unresolved import `crate::utils::setup_utils::windows_firewall`
  --> src\gpu_miner_adapter.rs:16:32
   |
16 | use crate::utils::setup_utils::windows_firewall::add_firewall_rule;
   |                                ^^^^^^^^^^^^^^^^ could not find `windows_firewall` in `setup_utils`

error[E0432]: unresolved import `crate::utils::setup_utils::windows_firewall`
  --> src\node_adapter.rs:24:32
   |
24 | use crate::utils::setup_utils::windows_firewall::add_firewall_rule;
   |                                ^^^^^^^^^^^^^^^^ could not find `windows_firewall` in `setup_utils`

error[E0432]: unresolved import `crate::utils::setup_utils::windows_firewall`
  --> src\p2pool_adapter.rs:19:32
   |
19 | use crate::utils::setup_utils::windows_firewall::add_firewall_rule;
   |                                ^^^^^^^^^^^^^^^^ could not find `windows_firewall` in `setup_utils`

error[E0432]: unresolved import `crate::utils::setup_utils::windows_firewall`
  --> src\wallet_adapter.rs:22:32
   |
22 | use crate::utils::setup_utils::windows_firewall::add_firewall_rule;
   |                                ^^^^^^^^^^^^^^^^ could not find `windows_firewall` in `setup_utils`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `tari-universe` (bin "tari-universe") due to 4 previous errors
```

**Comment by brianp** [comment]
This was tested on Windows 11, and 10. It seemed to be a bit intermittent, but it generally made things _better_. We're merging for now, with the understanding that once tauri v2 is in, we'll be able to continue to improve this issue, easier than we can now. So it's a small win with a bright future.

**Comment by Tas4tari** [comment]
Tested on Windows 11. i did a fresh install of 0.7.7 and did not receive a pop up on Windows asking for permission to run xmrig, mmproxy, sha_p2pool etc

**Pull request merged**
