### PR TITLE
feat(ui): tab focus accessibility outline for buttons

### PR DESCRIPTION
**Pull request by peps**
This PR adds a green outline to button elements when they are tab focused with the keyboard. If the user focuses on a  button by clicking with a mouse, the green outline does not show. This is just for keyboard accessibility. 

CleanShot 2024-11-06 at 18 24 55

CleanShot 2024-11-06 at 18 25 19

https://www.loom.com/share/1676d72209904b99b1a78d1ab123af5a?sid=913dd109-ea68-44a5-8375-20901b03a9fc

CleanShot 2024-11-07 at 17 29 50

### CODE REVIEW

**Comment by peps** [comment]
@shanimal08 FYI, I had to change the Mining Button animation around a bit since the `overflow: hidden` was hiding the focus outline.

**Review by brianp — APPROVED** [review]
LGTM.

It becomes notable that the toggle switches are skipped over in the settings panel, and can not be changed via the keyboard.

**Comment by shanimal08** [comment]
> LGTM.
> 
> It becomes notable that the toggle switches are skipped over in the settings panel, and can not be changed via the keyboard.

eek that's my fault - will update separately!

**Review by shanimal08 — APPROVED** [review]

**Comment by peps** [comment]
> > LGTM.
> > It becomes notable that the toggle switches are skipped over in the settings panel, and can not be changed via the keyboard.
> 
> eek that's my fault - will update separately!

@shanimal08 no worries! Ill update the toggle buttons

**Comment by peps** [comment]
@shanimal08 @brianp Ok, toggle switch targeting is in. 

image

**Pull request merged**
