### PR TITLE
feat(ui): temp paper wallet QR code

### PR DESCRIPTION
**Pull request by shanimal08**
Description
---
- quick QR code implementation so testing on aurora can start

How Has This Been Tested?
---
- ~~locally with testflight aurora, though nothing happened after the app opened (assuming because the local network  is esmeralda and aurora is on nextnet)~~ see comment

Screenshot 2024-10-15 at 15 45 32

What process can a PR reviewer use to test or verify this change?
---
- set the `paper_wallet_enabled` flag 
- load and scan the QR code in wallet settings

### CODE REVIEW

**Comment by Anziskavds** [comment]
This tested successfully on Tari Universe 0.5.27 when setting the "paper_wallet_enabled" to true and scanning from an iPhoe 12 iOS 17.6.1 on Tari Aurora Nextnet v0.28.0 (b776).

**Comment by brianp** [comment]
@Anziskavds what did the passphrase look like? As we just merged an update to this function. 

Was it random characters or 5 English based words?

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version NextNet 0.5.27, and I do not see the QR code in Wallet settings, @Anziskavds confirmed this is no longer working on Mac as well:

Screenshot (137)
Screenshot (136)

**Comment by brianp** [comment]
Two things need to be true here.

`paper_wallet_enabled` set to `true` in the config.

And "Experimental Features" must be enabled within the app settings. 

Then the paper wallet will appear at the **bottom** of the wallet settings.

**Comment by shanimal08** [comment]
> Two things need to be true here.
> 
> `paper_wallet_enabled` set to `true` in the config.
> 
> And "Experimental Features" must be enabled within the app settings.
> 
> Then the paper wallet will appear at the **bottom** of the wallet settings.

ah yes, so sorry @Tas4tari @Anziskavds i didn't add the experimental settings note in the description - will add!

**Comment by Anziskavds** [comment]
Retested on Testnet 0.5.28 on a MacBook Air 13 inch M1 2020 and it tested successfully. 
image

**Comment by Tas4tari** [comment]
Tested this on Windows 11, v0.5.28 and on Aurora Android app which was downloaded from the PlayStore.
Failed to recover on Aurora, error is the same as what was received here:
https://github.com/tari-project/wallet-android/issues/1235
Tested with the Aurora app on iPhone which workedd successsfully. (The build was downloaded from the app store)

**Pull request merged**
