### PR TITLE
fix(ui): design feedback ui tweaks

### PR DESCRIPTION
**Pull request by peps**
- Adjusted padding and border radius on sidebar container

- Removed divider line between tiles and start mining button

- Adjusted spacing on mining stat tiles to make them tighter

- Adjusted large sidebar text to blend it in to the background more and moved it closer to the edge

- Added `toLocaleString` to ruler numbers so they have a comma

CleanShot 2024-10-09 at 17 32 55

### CODE REVIEW

**Comment by shanimal08** [comment]
i'd be happier if we made it `-40px` instead? watcha think? @peps :D

**Comment by peps** [comment]
> i'd be happier if we made it `-40px` instead? watcha think? @peps :D

@shanimal for sure, ill tweak it. It's actually not cut off that much on my local...

**Review by shanimal08 — APPROVED** [review]

**Comment by Anziskavds** [comment]
Tested successfully on Testnet 0.5.17 on MacBook Air 13 inch M1 2020 on Sonoma 14.5.

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, however I still see the double line Karim mentioned at block height
Screenshot (40)

**Pull request merged**
