### PR TITLE
fix: save issue reference in store

### PR DESCRIPTION
**Pull request by mmrrnn**
[#1013](https://github.com/tari-project/universe/issues/1013)

Save issue reference in the AppStateStore so reference number is not disappearing after reopening settings.

[Screencast from 11-22-2024 10:41:00 AM.webm](https://github.com/user-attachments/assets/933af946-f0c7-44ad-a799-66e2903966fb)

### CODE REVIEW

**Comment by brianp** [comment]
What happens if they submit again?

**Comment by mmrrnn** [comment]
It's overwritten

**Comment by brianp** [comment]
I'm okay with that for now, although I suspect in the future they may wish for a history.

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, app version 0.7.7

**Pull request merged**
