### PR TITLE
feat(ui): persistent visual mode

### PR DESCRIPTION
**Pull request by mmrrnn**

### CODE REVIEW

**Review by shanimal08 — APPROVED** [review]

**Review by stringhandler — APPROVED** [review]

**Comment by mmrrnn** [comment]
Wait with merging :alert:

**Comment by mmrrnn** [comment]
Animation is triggered even when starting the app

**Review by stringhandler — APPROVED** [review]

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, app version 0.6.4. When I disable visual mode and restart the app. I find that the change persists and I do not see the tower or block animations

**Comment by Anziskavds** [comment]
Tested successfully on MacBook Air 13 inch M1 2020 on Testnet v0.6.4.

**Pull request merged**
