### PR TITLE
feat(ui): earnings recap

### PR DESCRIPTION
**Pull request by shanimal08**
Description
---
- refactored win/lose animation triggers to check transactions (remove balance change checks since we have transaction history now)
  - also includes moving some of the mining hooks & store updaters around and into `useMiningStatesSync`
  - moved wallet, transaction, and mining metrics 'fetch' functions out of the stores and into their own hooks so they can be used independently of the stores
- store missed wins if `canAnimate` was false for a won block
- show the recap once window is focused again
- adjusted `Earnings` styling to cater for the new recap section
- updated the debug settings block time counter to use block_time from base_node instead of the display block height (also updates when not mining)

Motivation and Context
---
- no ticket but resolves Recap History [(figma)](https://www.figma.com/design/Tyh0UcWVo44z66gYHd0TBs/Tari-Universe-Planning-%26-Wires?node-id=2922-148285&node-type=canvas&m=dev)

How Has This Been Tested?
---

- locally

### **recap after minimised:**

https://github.com/user-attachments/assets/7b071ea8-8a1b-48ad-93cd-7218146bf8cc

----

### **recap after just being on a different screen:**

(and a win right after focusing, cos i am DOMINATING esmeralda apparently)

https://github.com/user-attachments/assets/bacc978e-d6f4-4eb0-8bed-ad9bf6069aa1

----

### **win while focused still works as normal + debug block time:**

https://github.com/user-attachments/assets/45f3f7e4-6a0d-49db-868e-3982aa374f99

----

**~~still trying to get a fail animation, but i think i'm the only person on esme right now or something, but it does work :3~~**

### **lose while focused still working as before:**

https://github.com/user-attachments/assets/9aa6b04e-f3fa-44aa-8305-dd14196d74f6

----

What process can a PR reviewer use to test or verify this change?
---

- run app
- check if winning and losing a block still works as before 
- leave the app minimized or on a non-focused screen for a while
  - come back and check that the blocks you won previously are accounted for

### CODE REVIEW

**Comment by mmrrnn** [comment]
Wow, great job! :+1:

**Review by brianp — APPROVED** [review]
Tested. Looks good.

image


Clippy seems to have a lot of unrelated GPUStats errors. So I'm going to merge this despite the clippy CI failure.

**Comment by shanimal08** [comment]
dang @brianp 10 blocks !

**Comment by Tas4tari** [comment]
Unable to confirm as of yet on Nextnet v0.5.22 as I have not won any blocks etc

**Comment by Anziskavds** [comment]
I am unable to test this. I haven't won any tXTM yet on Testnet 0.5.22.

**Pull request merged**
