### PR TITLE
feat: custom cpu and gpu usage levels

### PR DESCRIPTION
**Pull request by PanchoBubble**
## Adds custom power settings

* Adds new `MiningMode` Custom
* Adds `ocl` to check device `max_wg_size` instead of using the hardcoded 800
* New `get_max_consumption_levels`
    * Fetches `max_wg_size` and amount of CPU cores when selecting custom mode to set max settings on range sliders
* `set_mode` now accepts new custom power levels
* New `custom_power_levels_enabled` feature flag

https://www.loom.com/share/bc10b28200f048a896301a3058ca571b

### CODE REVIEW

**Comment by brianp** [comment]
@PanchoBubble any reason this is still in draft?

**Comment by PanchoBubble** [comment]
> @PanchoBubble any reason this is still in draft?

Yes I'll push a feature flag just in case and I wastrying to fic clippy.
Also need to confirm if we can fix the CI, it looks like linux builder doesn't like the new dependency OCL I introduced for getting gpu data

**Comment by brianp** [comment]
I've asked @leet4tari to look at the opencl issue in ci

**Comment by leet4tari** [comment]
This will need openCL for Linux in the release and ci workflow. Not sure for other OS, thou builds for OSX ARM64.

**Comment by brianp** [comment]
@PanchoBubble - This branch will need updating. @leet4tari has added opencl setup to CI, so merging main should receive those updates.

He said windows builds were still having an issue and may require additional dev configuration. What system are you dev'ing on?

**Comment by PanchoBubble** [comment]
@brianp I'm using mac

**Comment by brianp** [comment]
I might be able to devote some time to testing and expanding this next week.

**Comment by PanchoBubble** [comment]
@brianp  don't merge yet, testing [release build](https://github.com/PanchoBubble/universe/actions/runs/11663057107) for windows, after that I'll install binary on my desktop if successful

**Comment by PanchoBubble** [comment]
@brianp it just works now

**Comment by brianp** [comment]
Typo:
image

> Choose how many threads you want your GPU to **allocat** to mining

**Comment by brianp** [comment]
Warning text for high CPU/GPU usage needs some work. It's a bit aggressive.

**Review by brianp — APPROVED** [review]

**Comment by Anziskavds** [comment]
Tested unsuccessfully on a Macbook Air 13 inch M1 2020 on Testnet v0.5.63. When a user sets a custom CPU or GPU they get stuck on loading. I waited about 1omin and I'm still inloading state. My animation blocks also disappeared.
image

**Pull request merged**
